// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZjgYFbYIAVVN6xQriPIe5kycvv1KJKBQ',
    appId: '1:82661131750:web:20adb28a833e16428d4227',
    messagingSenderId: '82661131750',
    projectId: 'smart-farming-9ac26',
    authDomain: 'smart-farming-9ac26.firebaseapp.com',
    storageBucket: 'smart-farming-9ac26.firebasestorage.app',
    measurementId: 'G-4CJ5FLZGZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL6LtLPPgHLCsLtdlwoFX0CeKeePYylAQ',
    appId: '1:82661131750:android:132aaa0e836ab58f8d4227',
    messagingSenderId: '82661131750',
    projectId: 'smart-farming-9ac26',
    storageBucket: 'smart-farming-9ac26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2UpJYskeWbatIkluo6lmGHFNwbdSlKGw',
    appId: '1:82661131750:ios:5429febc76481bfe8d4227',
    messagingSenderId: '82661131750',
    projectId: 'smart-farming-9ac26',
    storageBucket: 'smart-farming-9ac26.firebasestorage.app',
    iosClientId: '82661131750-a5kldkid34q8or9sq2ft0rg0of08tf11.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2UpJYskeWbatIkluo6lmGHFNwbdSlKGw',
    appId: '1:82661131750:ios:5429febc76481bfe8d4227',
    messagingSenderId: '82661131750',
    projectId: 'smart-farming-9ac26',
    storageBucket: 'smart-farming-9ac26.firebasestorage.app',
    iosClientId: '82661131750-a5kldkid34q8or9sq2ft0rg0of08tf11.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfarming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZjgYFbYIAVVN6xQriPIe5kycvv1KJKBQ',
    appId: '1:82661131750:web:94c3894642906e798d4227',
    messagingSenderId: '82661131750',
    projectId: 'smart-farming-9ac26',
    authDomain: 'smart-farming-9ac26.firebaseapp.com',
    storageBucket: 'smart-farming-9ac26.firebasestorage.app',
    measurementId: 'G-VL6JC830C0',
  );

}

/*import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
); */